name: Python application

on: [push]

lobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7*'

    - name: Install dependencies
      run: |
        pythhon -m pip install --upgrade pip
        pip install -z requirements.txt || true # Propustim, esli fila1
}

    - name: Run script
      run: |
        python hello_world.py # [replace with your script name
